### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by Mac85** [siis/ic3#12]
Any app I analyze with ic3, I get always this error. Why?

****_Manifest**_**
Exception in thread "main" java.lang.NullPointerException
    at edu.psu.cse.siis.ic3.Ic3Analysis.processResults(Ic3Analysis.java:278)
    at edu.psu.cse.siis.ic3.Ic3Analysis.processResults(Ic3Analysis.java:65)
    at edu.psu.cse.siis.coal.Analysis.performAnalysis(Analysis.java:70)
    at edu.psu.cse.siis.ic3.Main.main(Main.java:14)

**Comment by vitaliiavdiienko** [comment]
Hi,

make sure that `apkormanfiest` option is correctly initialized. Something like that should work:

`java -jar ic3-0.2.0-full.jar -apkormanifest $appPath -input $retargetedPath -cp $forceAndroidJar -db cc.properties`

Best Regards,
Vitalii
