### ISSUE TITLE
IC3 failed in Windows soot.CompilationDeathException:Couldn't resolve clas spath entry

### ISSUE THREAD

**Issue by peopleqinlei** [siis/ic3#18]
I want to run IC3 in windows,so I wrote a run.bat like this

run.bat
@echo off
set appPath=%1

set forceAndroidJar=H:\ic3\android.jar

rm -rf testspace
mkdir testspace

set appName=%appPath:~0,-4%

set retargetedPath=testspace\%appName%.apk\retargeted\retargeted\%appName%

rm -rf output/ic3/$appName.txt

java -Xmx8192m -jar RetargetedApp.jar %forceAndroidJar% %appPath% %retargetedPath%
java -Xmx8192m -jar ic3-0.1.0-full.jar -apkormanifest %appPath% -input %retargetedPath% -classpath %forceAndroidJar% -db cc.properties

rm -rf sootOutput

until the first java statement 
java -Xmx8192m -jar RetargetedApp.jar %forceAndroidJar% %appPath% %retargetedPath%
finished,everything is OK
but when the second
java -Xmx8192m -jar ic3-0.1.0-full.jar -apkormanifest %appPath% -input %retargetedPath% -classpath %forceAndroidJar% -db cc.properties
is executed,ERROR occured

H:\ic3>java -Xmx8192m -jar ic3-0.1.0-full.jar -apkormanifest ActivityLifecycle2.
apk -classpath "H:\ic3\android.jar"  -input "testspace\ActivityLifecycle2.apk\re
targeted\retargeted\ActivityLifecycle2"  -db cc.properties
Exception in thread "main" soot.CompilationDeathException: Couldn't resolve clas
spath entry H:\ic3\android.jar:testspace\ActivityLifecycle2.apk\retargeted\retar
geted\ActivityLifecycle2:: java.io.IOException: 文件名、目录名或卷标语法不正确。

```
    at soot.SourceLocator.explodeClassPath(SourceLocator.java:426)
    at soot.SourceLocator.getClassSource(SourceLocator.java:64)
    at soot.SootResolver.bringToHierarchy(SootResolver.java:200)
    at soot.SootResolver.bringToSignatures(SootResolver.java:252)
    at soot.SootResolver.bringToBodies(SootResolver.java:288)
    at soot.SootResolver.processResolveWorklist(SootResolver.java:164)
    at soot.SootResolver.resolveClass(SootResolver.java:129)
    at soot.Scene.tryLoadClass(Scene.java:629)
    at soot.Scene.loadBasicClasses(Scene.java:1200)
    at soot.Scene.loadNecessaryClasses(Scene.java:1279)
    at edu.psu.cse.siis.ic3.SetupApplication.initializeSoot(SetupApplication
```

.java:252)
        at edu.psu.cse.siis.ic3.SetupApplication.calculateSourcesSinksEntrypoint
s(SetupApplication.java:125)
        at edu.psu.cse.siis.ic3.Ic3Analysis.initializeAnalysis(Ic3Analysis.java:
125)
        at edu.psu.cse.siis.ic3.Ic3Analysis.initializeAnalysis(Ic3Analysis.java:
64)
        at edu.psu.cse.siis.coal.Analysis.performAnalysis(Analysis.java:66)
        at edu.psu.cse.siis.ic3.Main.main(Main.java:14)

I think,maybe the reason is format of Windows filepath differences from Linux
Can somebody helps me?
THX!

**Comment by docteau** [comment]
Hi,

Sorry, but I am very unfamiliar with issues related to Windows. It does look like it could be a problem with file paths.

Regards,
Damien

**Comment by jxnu707** [comment]
Change it into Linux.
Actually,I got the same promble like you.it prove IC3 does not work very well in windows.
But it works well in Linux now.
