### ISSUE TITLE
Analysis Exception 

### ISSUE THREAD

**Issue by wenhuizhang** [siis/ic3#19]
@docteau   @aegiryy  @hvijay I was trying to analyze sample apk files you guys provided here 'http://siis.cse.psu.edu/android_sec_tutorial.html' , and got the following log: 

Do you mind if help explain why I encountered an exception please?

```
*****Manifest*****
Exception in thread "main" java.lang.NullPointerException
    at edu.psu.cse.siis.ic3.Ic3Analysis.processResults(Ic3Analysis.java:278)
    at edu.psu.cse.siis.ic3.Ic3Analysis.processResults(Ic3Analysis.java:65)
    at edu.psu.cse.siis.coal.Analysis.performAnalysis(Analysis.java:70)
    at edu.psu.cse.siis.ic3.Main.main(Main.java:14)
```

The full log is as below: 

```
wenhui@wenhui:~/Downloads/ic3/target$ java -Xmx4g -jar ./ic3-0.2.0-full.jar  -apkormanifest ../../android-sec-tutorial-apk/FriendTracker.apk -input ../../ -cp /home/wenhui/Downloads/ic3-0.2.0/android.jar 
Warning: java.lang.invoke.LambdaMetafactory is a phantom class!
Warning: java.lang.ref.Finalizer is a phantom class!
Warning: org.siislab.tutorial.friendtracker.FriendTracker is a phantom class!
Warning: org.siislab.tutorial.friendtracker.FriendTrackerControl is a phantom class!
Warning: org.siislab.tutorial.friendtracker.FriendProvider is a phantom class!
Warning: org.siislab.tutorial.friendtracker.BootReceiver is a phantom class!
[main] INFO  soot.jimple.infoflow.entryPointCreators.AndroidEntryPointCreator  - Generated main method:
    public static void dummyMainMethod()
    {
        int $i0;

        $i0 = 0;

     label1:
        if $i0 == 8 goto label1;

        return;
    }

[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
[Spark] Pointer Assignment Graph in 0.0 seconds.
[Spark] Type masks in 0.0 seconds.
[Spark] Pointer Graph simplified in 0.0 seconds.
[Spark] Propagation in 0.0 seconds.
[Spark] Solution found in 0.0 seconds.
Callback analysis done.
Warning: LinearLayout is a phantom class!
Warning: org.siislab.tutorial.friendtracker.LinearLayout is a phantom class!
Warning: android.view.LinearLayout is a phantom class!
Warning: TextView is a phantom class!
Warning: org.siislab.tutorial.friendtracker.TextView is a phantom class!
Warning: android.view.TextView is a phantom class!
Warning: Button is a phantom class!
Warning: org.siislab.tutorial.friendtracker.Button is a phantom class!
Warning: android.view.Button is a phantom class!
Found 1 layout controls in file res/layout/main.xml
[main] INFO  edu.psu.cse.siis.ic3.SetupApplication  - Entry point calculation done.
Warning: org.siislab.tutorial.friendtracker.FriendTracker is a phantom class!
Warning: org.siislab.tutorial.friendtracker.FriendTrackerControl is a phantom class!
Warning: org.siislab.tutorial.friendtracker.FriendProvider is a phantom class!
Warning: org.siislab.tutorial.friendtracker.BootReceiver is a phantom class!
[main] INFO  soot.jimple.infoflow.entryPointCreators.AndroidEntryPointCreator  - Generated main method:
    public static void dummyMainMethod()
    {
        int $i0;

        $i0 = 0;

     label1:
        if $i0 == 8 goto label1;

        return;
    }

[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
[Spark] Pointer Assignment Graph in 0.0 seconds.
[Spark] Type masks in 0.0 seconds.
[Spark] Pointer Graph simplified in 0.0 seconds.
[Spark] Propagation in 0.0 seconds.
[Spark] Solution found in 0.0 seconds.
[main] INFO  edu.psu.cse.siis.coal.PropagationSceneTransformer  - Solving propagation problem (iteration 0)
[main] INFO  edu.psu.cse.siis.coal.PropagationSceneTransformer  - Reached a fixed point
Transforming android.content.Intent... 
Transforming android.content.IntentFilter... 
Transforming android.os.Bundle... 
Transforming android.content.ComponentName... 
Transforming android.app.Activity... 
Transforming dummyMainClass... 
Transforming org.siislab.tutorial.friendtracker.FriendTracker... 
Transforming org.siislab.tutorial.friendtracker.FriendTrackerControl... 
Transforming org.siislab.tutorial.friendtracker.FriendProvider... 
Transforming org.siislab.tutorial.friendtracker.BootReceiver... 

*****Manifest*****
Exception in thread "main" java.lang.NullPointerException
    at edu.psu.cse.siis.ic3.Ic3Analysis.processResults(Ic3Analysis.java:278)
    at edu.psu.cse.siis.ic3.Ic3Analysis.processResults(Ic3Analysis.java:65)
    at edu.psu.cse.siis.coal.Analysis.performAnalysis(Analysis.java:70)
    at edu.psu.cse.siis.ic3.Main.main(Main.java:14)
wenhui@wenhui:~/Downloads/ic3/target$ java -Xmx4g -jar ./ic3-0.2.0-full.jar  -apkormanifest ../../android-sec-tutorial-apk/  -input ../../ -cp /home/wenhui/Downloads/ic3-0.2.0/android.jar 
[main] ERROR edu.psu.cse.siis.ic3.Ic3Analysis  - Could not process application null
edu.psu.cse.siis.coal.FatalAnalysisException: Could not process manifest file ../../android-sec-tutorial-apk/: java.io.FileNotFoundException: ../../android-sec-tutorial-apk (Is a directory)
    at edu.psu.cse.siis.ic3.Ic3Analysis.initializeAnalysis(Ic3Analysis.java:149)
    at edu.psu.cse.siis.ic3.Ic3Analysis.initializeAnalysis(Ic3Analysis.java:65)
    at edu.psu.cse.siis.coal.Analysis.performAnalysis(Analysis.java:66)
    at edu.psu.cse.siis.ic3.Main.main(Main.java:14)
wenhui@wenhui:~/Downloads/ic3/target$ java -Xmx4g -jar ./ic3-0.2.0-full.jar  -apkormanifest ../../android-sec-tutorial-apk/*.apk -input ../../ -cp /home/wenhui/Downloads/ic3-0.2.0/android.jar 
Warning: java.lang.invoke.LambdaMetafactory is a phantom class!
Warning: java.lang.ref.Finalizer is a phantom class!
Warning: org.siislab.tutorial.friendseed.FriendSeed is a phantom class!
[main] INFO  soot.jimple.infoflow.entryPointCreators.AndroidEntryPointCreator  - Generated main method:
    public static void dummyMainMethod()
    {
        int $i0;

        $i0 = 0;

     label1:
        if $i0 == 2 goto label1;

        return;
    }

[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
[Spark] Pointer Assignment Graph in 0.0 seconds.
[Spark] Type masks in 0.0 seconds.
[Spark] Pointer Graph simplified in 0.0 seconds.
[Spark] Propagation in 0.0 seconds.
[Spark] Solution found in 0.0 seconds.
Callback analysis done.
Warning: LinearLayout is a phantom class!
Warning: org.siislab.tutorial.friendseed.LinearLayout is a phantom class!
Warning: android.view.LinearLayout is a phantom class!
Warning: TextView is a phantom class!
Warning: org.siislab.tutorial.friendseed.TextView is a phantom class!
Warning: android.view.TextView is a phantom class!
Found 1 layout controls in file res/layout/main.xml
[main] INFO  edu.psu.cse.siis.ic3.SetupApplication  - Entry point calculation done.
Warning: org.siislab.tutorial.friendseed.FriendSeed is a phantom class!
[main] INFO  soot.jimple.infoflow.entryPointCreators.AndroidEntryPointCreator  - Generated main method:
    public static void dummyMainMethod()
    {
        int $i0;

        $i0 = 0;

     label1:
        if $i0 == 2 goto label1;

        return;
    }

[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
[Spark] Pointer Assignment Graph in 0.0 seconds.
[Spark] Type masks in 0.0 seconds.
[Spark] Pointer Graph simplified in 0.0 seconds.
[Spark] Propagation in 0.0 seconds.
[Spark] Solution found in 0.0 seconds.
[main] INFO  edu.psu.cse.siis.coal.PropagationSceneTransformer  - Solving propagation problem (iteration 0)
[main] INFO  edu.psu.cse.siis.coal.PropagationSceneTransformer  - Reached a fixed point
Transforming android.content.Intent... 
Transforming android.content.IntentFilter... 
Transforming android.os.Bundle... 
Transforming android.content.ComponentName... 
Transforming android.app.Activity... 
Transforming dummyMainClass... 
Transforming org.siislab.tutorial.friendseed.FriendSeed... 

*****Manifest*****
Exception in thread "main" java.lang.NullPointerException
    at edu.psu.cse.siis.ic3.Ic3Analysis.processResults(Ic3Analysis.java:278)
    at edu.psu.cse.siis.ic3.Ic3Analysis.processResults(Ic3Analysis.java:65)
    at edu.psu.cse.siis.coal.Analysis.performAnalysis(Analysis.java:70)
    at edu.psu.cse.siis.ic3.Main.main(Main.java:14)

```

**Comment by docteau** [comment]
Hi,

It looks like the input classes are not found. The problem is likely where you set `-input ../../`. I assume that the classes are in some subdirectory of ~/Downloads.

Damien
