### ISSUE TITLE
Is this a bug in ic3-0.2.0 ? The same apk can be solved well in ic3-0.1.0

### ISSUE THREAD

**Issue by snowcool** [siis/ic3#24]
*****Manifest*****
Exception in thread "main" java.lang.NullPointerException
        at edu.psu.cse.siis.ic3.Ic3Analysis.processResults(Ic3Analysis.java:278)
        at edu.psu.cse.siis.ic3.Ic3Analysis.processResults(Ic3Analysis.java:65)
        at edu.psu.cse.siis.coal.Analysis.performAnalysis(Analysis.java:70)
        at edu.psu.cse.siis.ic3.Main.main(Main.java:14)

**Comment by docteau** [comment]
Hi,

There is an issue with a null pointer exception when no output is specified. In order to avoid this, either use the -protobuf or -db option (see http://siis.cse.psu.edu/ic3/installation.html for how to use these options).

Best,
Damien
