### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by LeeHaofeng** [siis/ic3#35]
NullPointerException occurs when I use commond below.
java -jar ic3.jar -apkormanifest  -input -db

details:
Exception in thread "main" java.lang.NullPointerException
	at java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2741)
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2757)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3234)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:913)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:375)
	at edu.psu.cse.siis.coal.Model.loadModelFromCompiledFile(Model.java:172)
	at edu.psu.cse.siis.coal.Analysis.loadModel(Analysis.java:90)
	at edu.psu.cse.siis.coal.Analysis.performAnalysis(Analysis.java:58)
	at edu.psu.cse.siis.ic3.Main.main(Main.java:14)

The website cannot be accessed.
http://siis.cse.psu.edu/ic3/

**Comment by JordanSamhi** [comment]
Hi @HaofLi 
The exception happens because you do not give any input to ic3, so it is trying to load a file that does not exist.
The options you are using need arguments.
